apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-chart.fullname" . }}
  labels:
    {{- include "minio-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "minio-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiTargetPort }}
      protocol: TCP
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consoleTargetPort }}
      protocol: TCP
