---
- name: Restart SSH
  ansible.builtin.service:
    name: "{{ security_sshd_service }}"
    state: restarted
  become: true

- name: Reload UFW
  community.general.ufw:
    state: enabled
  become: true

- name: Restart fail2ban
  ansible.builtin.service:
    name: "{{ security_fail2ban_service }}"
    state: restarted
    enabled: true
  become: true
