apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-chart.fullname" . }}
  labels:
    {{- include "redis-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis-chart.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        {{- include "redis-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "redis-chart.serviceAccountName" . }}
      containers:
        - name: {{ include "redis-chart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          ports:
            - name: redis
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "redis-chart.pvcName" .) }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
