apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: edusphere
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: edusphere
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: change-me-minio-password
