# EduSphere – Dev server (update ansible_host from Terraform output)

[edusphere_dev]
edusphere-dev ansible_host=32.197.201.165

[edusphere_dev:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/hmed_amed/.ssh/devops-key.pem
ansible_python_interpreter=/usr/bin/python3
ansible_become=true

project_dir=/opt/edusphere
github_repo=https://github.com/ahmed1707hamed-tech/EduSpere.git
github_branch=main
