apiVersion: v2
name: content-chart
description: Helm chart for the EduSphere content microservice
type: application
version: 0.1.1
appVersion: "1.0.0"
keywords:
  - edusphere
  - content
  - microservice
maintainers:
  - name: EduSphere Team
