{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusphere.secretName" . }}
  labels:
    {{- include "edusphere.labels" . | nindent 4 }}
    app.kubernetes.io/name: app-secret
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
